apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-nfs-client-provisioner
  namespace: hospital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-nfs-client-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq-nfs-client-provisioner
    spec:
      serviceAccount: nfs-provisioner
      containers:
        - name: rabbitmq-nfs-client-provisioner
          #image: registry.cn-hangzhou.aliyuncs.com/open-ali/nfs-client-provisioner
          image: registry.cn-shanghai.aliyuncs.com/jieee/nfs-client-provisioner:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nfs-client-root
              mountPath:  /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: rabbitmq/nfs
            - name: NFS_SERVER
              value: 192.168.0.234
            - name: NFS_PATH
              value: /u/rabbitmq
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.0.234
            path: /u/rabbitmq
